spring:
  datasource:
    username: home_health_care
    password: home_health_care
    url: jdbc:mysql://localhost:3306/home_health_care
    
  jpa:
    hibernate:
      ddl_auto: create
    show-sql: true    
  
  
  sql:
    init:
      mode: always